plugins {
    id 'com.android.application'
    id 'com.google.gms.google-services'
}

android {
    namespace 'com.movieapp'
    compileSdk 35

    defaultConfig {
        applicationId 'com.movieapp'
        minSdk 23
        targetSdk 35
        versionCode 6
        versionName "1.4"
    }
}


dependencies {
    implementation platform('com.google.firebase:firebase-bom:34.2.0')
    implementation 'com.google.firebase:firebase-firestore'
    implementation 'com.google.firebase:firebase-auth'
    implementation 'com.google.android.gms:play-services-auth:21.4.0'
    implementation 'androidx.media3:media3-exoplayer:1.8.0'
    implementation 'androidx.media3:media3-ui:1.8.0'
    implementation 'androidx.documentfile:documentfile:1.0.1'
}
